<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class CheckoutSetting extends Model
{
    protected $fillable = [
        'store_id',
        'primary_color',
        'secondary_color',
        'logo_url',
        'banner_url',
        'banner_height',
        'enable_order_bump',
        'dark_mode',
        'button_text',
        'banner_message',
        'header_store_name_visible',
        'header_secure_badge',
        'header_logo_alignment',
        'header_bg_color',
        'header_icon_color',
        'announcement_bar_enabled',
        'announcement_bar_bg',
        'announcement_bar_text_color',
        'summary_title',
        'summary_default_expanded',
        'summary_show_discount',
        'summary_coupon_enabled',
        'step_title_font_size',
        'step_number_color',
        'input_border_radius',
        'step_button_color',
        'finalize_button_color',
        'step_card_background_color',
        'scarcity_enabled',
        'scarcity_type',
        'scarcity_text',
        'scarcity_title',
        'scarcity_countdown_minutes',
        'scarcity_font_color',
        'scarcity_counter_color',
        'scarcity_counter_text_color',
        'pix_confirmation_title',
        'pix_confirmation_message',
        'pix_confirmation_logo',
        'footer_text',
        'footer_show_cnpj',
        'footer_cnpj',
        'footer_show_store_name',
        'footer_show_payment_methods',
        'footer_show_contact_email',
        'footer_contact_email',
        'footer_show_whatsapp',
        'footer_whatsapp',
        'footer_show_address',
        'footer_address',
        'footer_show_terms',
        'footer_terms_url',
        'footer_show_privacy_policy',
        'footer_privacy_policy_url',
        'footer_show_return_policy',
        'footer_return_policy_url',
        'footer_text_color',
        'footer_background_color',
        'footer_show_security_icons',
        'footer_icon_color',
        'font_family',
        'font_size_base',
        'social_proofs_enabled',
        'pix_enabled',
        'pix_gateway_id',
        'pix_gateway_ids',
        'card_enabled',
        'card_gateway_id',
        'card_gateway_ids',
        'boleto_enabled',
        'boleto_gateway_id',
        'boleto_gateway_ids',
        'default_payment_method',
        'pix_discount_percentage',
        'boleto_discount_percentage',
        'card_discount_percentage',
        'card_redirect_enabled',
        'card_redirect_url',
        'pix_redirect_enabled',
        'pix_redirect_url',
    ];

    protected $casts = [
        'enable_order_bump' => 'boolean',
        'dark_mode' => 'boolean',
        'header_store_name_visible' => 'boolean',
        'header_secure_badge' => 'boolean',
        'announcement_bar_enabled' => 'boolean',
        'summary_show_discount' => 'boolean',
        'summary_default_expanded' => 'boolean',
        'summary_coupon_enabled' => 'boolean',
        'scarcity_enabled' => 'boolean',
        'scarcity_countdown_minutes' => 'integer',
        'footer_show_cnpj' => 'boolean',
        'footer_show_store_name' => 'boolean',
        'footer_show_payment_methods' => 'boolean',
        'footer_show_contact_email' => 'boolean',
        'footer_show_whatsapp' => 'boolean',
        'footer_show_address' => 'boolean',
        'footer_show_terms' => 'boolean',
        'footer_contact_email' => 'string',
        'footer_whatsapp' => 'string',
        'footer_address' => 'string',
        'footer_show_privacy_policy' => 'boolean',
        'footer_show_return_policy' => 'boolean',
        'footer_show_security_icons' => 'boolean',
        'social_proofs_enabled' => 'boolean',
        'pix_enabled' => 'boolean',
        'card_enabled' => 'boolean',
        'boleto_enabled' => 'boolean',
        'pix_gateway_id' => 'integer',
        'pix_gateway_ids' => 'array',
        'card_gateway_id' => 'integer',
        'card_gateway_ids' => 'array',
        'boleto_gateway_id' => 'integer',
        'boleto_gateway_ids' => 'array',
        'default_payment_method' => 'string',
        'pix_discount_percentage' => 'decimal:2',
        'boleto_discount_percentage' => 'decimal:2',
        'card_discount_percentage' => 'decimal:2',
        'card_redirect_enabled' => 'boolean',
        'pix_redirect_enabled' => 'boolean',
    ];

    public function store()
    {
        return $this->belongsTo(Store::class);
    }
}
